### ISSUE TITLE
请问是否可以像 z-paging 一样支持单位 px/rpx 的选择？

### ISSUE THREAD

**Issue by kosuke-zhang** [SmileZXLee/uni-z-tabs#4]
我们用于 APP 开发，所有页面都是以 px 为基准，希望作者可以支持下单位切换

**Comment by SmileZXLee** [comment]
好的

**Comment by kosuke-zhang** [comment]
想自己改，但又对组件不熟悉，怕搞的四不像，等大佬了🫣

**Comment by SmileZXLee** [comment]
已支持，但未发布插件市场，可在github中下载尝试下

**Comment by kosuke-zhang** [comment]
> 已支持，但未发布插件市场，可在github中下载尝试下

太感谢了，多谢大佬，恕我直言这是我在插件市场中能找到的最好用的tabs组件👍

**Comment by SmileZXLee** [comment]
谢谢您的支持和鼓励~
